# Generated by Django 4.2.4 on 2023-08-17 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lista', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.usuario')),
                ('nombre_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.candidato')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.lista'),
        ),
    ]
