# Generated by Django 4.2.4 on 2023-08-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/images/', verbose_name='Image'),
        ),
    ]
